### ISSUE TITLE
Append to an existing table in SQL

### ISSUE THREAD

**Issue by 1sol** [titan550/bcpy#11]
How can we go about appending additional rows to an existing table?

The append option doesn't seem to work.

`bcpy.SqlTable(sql_config, table=table_name, if_exists='append')`

**Comment by titan550** [comment]
Please use the 

> use_existing_table=True

 argument.

https://github.com/titan550/bcpy/blob/f57aadf8857c5bcb571d85cf4a837b3ce816312e/bcpy/data_objects.py#L146
