### ISSUE TITLE
use_existing_sql_table does not work

### ISSUE THREAD

**Issue by saman49mondia** [titan550/bcpy#15]
Hi John, I am using your code to do bulk insert but every time I run it, it drops table and re-creates it although I set `use_existing_sql_table=True`.

**Comment by titan550** [comment]
I reviewed the code and I could not see the way it can happen.

1. Please share the working Python code that drops SQL table and recreates it.
1. How do you know if the table is dropped and recreated each time?

**Comment by saman49mondia** [comment]
Hi John, 

1- here is the code I used:
![image](https://user-images.githubusercontent.com/43862678/80316688-83734000-87ff-11ea-8831-6a22ab223757.png)

2- I checked table before and after bulk insert and it converted all columns into VARCHAR(MAX). I also get running query on machine and it was look like this:
```
INSERT
    bulk dbo.Table_Name
    (
        [Col1] nvarchar(MAX) collate Latin1_General_CI_AS,
        [Col2] nvarchar(MAX) collate Latin1_General_CI_AS,
        [Col3] nvarchar(MAX) collate Latin1_General_CI_AS,
        [Col4] nvarchar(MAX) collate Latin1_General_CI_AS,
        [Col5] nvarchar(MAX) collate Latin1_General_CI_AS,
        [Col6] nvarchar(MAX) collate Latin1_General_CI_AS
    )
    WITH
    (
        ROWS_PER_BATCH=10000)
```

**Comment by titan550** [comment]
Which version are your running?

You can confirm you are running the latest version by running the commands below:
```bash
pip install --no-cache-dir --force-reinstall bcpy
pip list bcpy
```

**Comment by saman49mondia** [comment]
bcpy version: 0.1.8

**Comment by pyerbiz** [comment]
Same issue bcpy==0.1.8, python 3.6.9, SQL server. Bulk copy tool  15.0.13 Checked a few times now.

```
bdf = bcpy.DataFrame(df)
# this step doesn't modify the existing table in database. I checked the table structure/definition after refreshing the database and running below command.
sql_table = bcpy.SqlTable(sql_config, table=table_name)
```

this step changes the table according to the pandas df structure:

`bdf.to_sql(sql_table)`

I can say it follow pandas structure because -
I had an Identity column called ID in the table definition. In the pandas dataframe this value wasn't there in the dataframe. The data was loaded by dropping 'ID' column in the SQl table. When I kept column as Null in the dataframe, it was loaded as null in the SQL Table

**Comment by saman49mondia** [comment]
The data types are identical in Pandas and SQL server for me. The code converts them somehow to NVARCHAR(max) without pay attention to its own defined data type.

**Comment by pyerbiz** [comment]
@saman49mondia  I looked for the method `use_existing_sql_table ` and it was actually inside the `to_sql` function. This is not an issue. @titan550 I figured when you thought it was a bug. It might be something else for you, but not the `use_existing_sql_table = True` as this thread is talking about. 

`bdf.to_sql(sql_table,use_existing_sql_table = True) `

works with existing tables.

**Comment by saman49mondia** [comment]
@pyerbiz thank you. after I applied what you mentioned, it worked. So I should use param in **to_sql** not in table **SqlTable**
