### ISSUE TITLE
In both the SqlTable and SqlServer objects the with_krb_auth is not invoked when username and passowrd are None

### ISSUE THREAD

**Issue by jpwhite99** [titan550/bcpy#4]
Currently the data objects code is:
`@property
    def with_krb_auth(self):
        """Returns True if the object uses Kerberos for authentication.
        :return: Kerberos authentication eligibility
        :rtype: bool
        """
        if hasattr(self, 'username') and hasattr(self, 'password'):
            result = False
        else:
            result = True
        return result`

The hasattr function returns true if the property is defined even if it is None.
Suggested update:
`@property
    def with_krb_auth(self):
        """Returns True if the object uses Kerberos for authentication.
        :return: Kerberos authentication eligibility
        :rtype: bool
        """
        if self.username is not None and self.password is not None:
            result = False
        else:
            result = True
        return result`

**Comment by titan550** [comment]
Thank you for bringing it up. I will fix it in the next release hopefully next weekend ;)
