### ISSUE TITLE
Insert Into Existing Table Without Dropping It

### ISSUE THREAD

**Issue by yehoshuadimarsky** [titan550/bcpy#5]
Hey, love this library, definitely fills a big need. 
How can we expand this so that it doesn't automatically drop and recreate the target SQL table? My use case is to APPEND to a table, not replace it.

**Comment by jaghayev** [comment]
Love it as well, but also facing issue with APPEND - I thought maybe I was doing something wrong. It would great to have that functionality . Thanks

**Comment by yehoshuadimarsky** [comment]
for what it's worth, I ended up writing my own library for this - inspired by you. Check it out - https://github.com/yehoshuadimarsky/bcpandas.
